config/routes.rb
Rails.application.routes.draw do
  get 'page/usermanagement'

  get 'page/home'

  get 'page/contact'

  devise_for :users
  
  root 'page#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def active_for_authentication? 
     super && approved? 
   end 

   def inactive_message 
     if !approved? 
       :not_approved 
     else 
       super # Use whatever other message 
     end 
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  before_action :authenticate_user!, only: [:contact]
  
  def home
  end

  def contact
  end
  
  def usermanagement
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mmgmt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  
	<% if user_signed_in? %>
		<%= link_to "Sign out", destroy_user_session_path, method: :delete %><br />
	<% else %>
		<%= link_to "Sign in", new_user_session_path %><br />
		<%= link_to "Sign up", new_user_registration_path %><br />
	<% end %>
	
	<%= link_to "Home", page_home_path %><br />
	<%= link_to "Contact", page_contact_path %><br />
	
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/page/usermanagement.html.erb
<h1>Page#usermanagement</h1>
<p>Find me in app/views/page/usermanagement.html.erb</p>